=== ttab/newsdoc/newsdoc.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://github.com/ttab/newsdoc/document",
  "$ref": "#/$defs/Document",
  "$defs": {
    "Block": {
      "properties": {
        "id": {
          "type": "string",
          "description": "ID is the block ID,"
        },
        "uuid": {
          "type": "string",
          "description": "UUID is used to reference another Document in a block.",
          "format": "uuid"
        },
        "uri": {
          "type": "string",
          "description": "URI is used to reference another entity in a document.",
          "format": "uri"
        },
        "url": {
          "type": "string",
          "description": "URL is a browseable URL for the the block.",
          "format": "uri"
        },
        "type": {
          "type": "string",
          "description": "Type is the type of the block"
        },
        "title": {
          "type": "string",
          "description": "Title is the title/headline of the block, typically used in the presentation of the block."
        },
        "data": {
          "$ref": "#/$defs/DataMap",
          "description": "Data contains block data."
        },
        "rel": {
          "type": "string",
          "description": "Rel describes the relationship to the document/parent entity."
        },
        "role": {
          "type": "string",
          "description": "Role is used either as an alternative to rel, or for nuancing the relationship."
        },
        "name": {
          "type": "string",
          "description": "Name is a name for the block. An alternative to \"rel\" when relationship is a term that doesn't fit."
        },
        "value": {
          "type": "string",
          "description": "Value is a value for the block. Useful when we want to store a primitive value."
        },
        "contenttype": {
          "type": "string",
          "description": "ContentType is used to describe the content type of the block/linked entity if it differs from the type of the block."
        },
        "links": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Links are used to link to other resources and documents."
        },
        "content": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Content is used to embed content blocks."
        },
        "meta": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Meta is used to embed metadata"
        },
        "sensitivity": {
          "type": "string",
          "description": "Sensitivity can be use to communicate how the information in a block can be handled. It could f.ex. be set to \"internal\", to show that it contains information that must be removed or transformed before publishing."
        }
      },
      "additionalProperties": false,
      "type": "object",
      "description": "Block is the building block for data embedded in documents."
    },
    "DataMap": {
      "additionalProperties": {
        "type": "string"
      },
      "type": "object",
      "description": "DataMap is used as key -\u003e (string) value data for blocks."
    },
    "Document": {
      "properties": {
        "uuid": {
          "type": "string",
          "description": "UUID is a unique ID for the document, this can for example be a random v4 UUID, or a URI-derived v5 UUID.",
          "format": "uuid"
        },
        "type": {
          "type": "string",
          "description": "Type is the content type of the document."
        },
        "uri": {
          "type": "string",
          "description": "URI identifies the document (in a more human-readable way than the UUID).",
          "format": "uri"
        },
        "url": {
          "type": "string",
          "description": "URL is the browseable location of the document (if any).",
          "format": "uri"
        },
        "title": {
          "type": "string",
          "description": "Title is the title of the document, can be used as the document name, or the headline when the document is displayed."
        },
        "content": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Content is the content of the document, this is essentially what gets rendered on the page when you view a document."
        },
        "meta": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Meta is the metadata for a document, this could be things like teasers, open graph data, newsvalues."
        },
        "links": {
          "items": {
            "$ref": "#/$defs/Block"
          },
          "type": "array",
          "description": "Links are links to other resources and entities. This could be links to topics, categories and subjects for the document, or credited authors."
        },
        "language": {
          "type": "string",
          "description": "Language is the language used in the document as an IETF language tag. F.ex. \"en\", \"en-UK\", \"es\", or \"sv-SE\"."
        }
      },
      "additionalProperties": false,
      "type": "object",
      "description": "Document is a NewsDoc document."
    }
  }
}

=== ttab/newsdoc/testdata/TestValueExtractor/planning.json
{
  "uuid": "dc6397d0-aa34-4ba3-b95c-3aafe7ff5cb0",
  "type": "core/planning-item",
  "uri": "core://newscoverage/dc6397d0-aa34-4ba3-b95c-3aafe7ff5cb0",
  "title": "Svenska paralympier firas p√• Arlanda",
  "meta": [
    {
      "type": "core/planning-item",
      "data": {
        "end_date": "2024-09-09",
        "public": "false",
        "start_date": "2024-09-09",
        "tentative": "false",
        "date_tz": "Europe/Stockholm"
      }
    },
    {
      "type": "core/copy-group",
      "uuid": "e7a79452-f983-45db-9b39-64c87012c063"
    },
    {
      "type": "core/description",
      "data": {
        "text": "PARASPORT: Den svenska truppen till Paralympics firas vid hemkomst (13.30, Arlanda)."
      },
      "role": "internal"
    },
    {
      "type": "tt/slugline",
      "value": "paralympics"
    },
    {
      "type": "core/newsvalue",
      "value": "1"
    },
    {
      "id": "54ed5440-1fa7-4516-a13c-dfd4166e9f37",
      "type": "core/assignment",
      "title": "start prel 13.45: minst 1|800 tecken under eftermiddagen",
      "data": {
        "end": "2024-09-09T12:00:00Z",
        "end_date": "2024-09-09",
        "full_day": "false",
        "public": "true",
        "start": "2024-09-09T10:00:00Z",
        "start_date": "2024-09-09",
        "date_tz": "Europe/Stockholm"
      },
      "meta": [
        {
          "type": "core/assignment-type",
          "value": "text"
        }
      ],
      "links": [
        {
          "rel": "source-document",
          "type": "tt/wire",
          "title": "A newswire",
          "uuid": "1aedf55d-789a-4905-afe2-12d26a5c83c1"
        },
        {
          "uuid": "4f13347f-04b3-4f22-a992-9316d824b81f",
          "type": "core/article",
          "rel": "deliverable"
        }
      ]
    }
  ],
  "links": [
    {
      "uuid": "e7c9b5bf-7212-4402-98a5-8df555db3937",
      "type": "core/event",
      "title": "Untitled",
      "rel": "event"
    },
    {
      "uuid": "0730efa9-43f2-468d-979a-aaffc74d7582",
      "type": "core/section",
      "title": "Sport",
      "rel": "section"
    }
  ],
  "language": "sv-se"
}

=== ttab/newsdoc/testdata/TestValueExtractor/constructed.json
{
  "type": "example/constructed",
  "meta": [
    {
      "type": "example/collection",
      "links": [
        {
          "rel": "item",
          "data": {
            "end": "2025-10-17T07:00:00.000Z",
            "start": "2025-10-17T07:00:00.000Z"
          }
        },
        {
          "rel": "item",
          "data": {
            "date": "2025-10-19",
            "date_timezone": "Asia/Shanghai"
          }
        },
        {
          "rel": "item",
          "data": {
            "date": "2025-10-21"
          }
        }
      ]
    }
  ],
  "content": [
    {
      "type": "example/assumed-static-tz",
      "value": "2025-10-15"
    }
  ],
  "links": [
    {
      "rel": "point-in-time",
      "type": "example/pit",
      "data": {
        "timestamp": "2025-10-17T08:34:35+02:00"
      }
    }
  ]
}
